name: Upstream Sync

on:
  schedule:
    - cron: '0 ***' # 每小时执行一次
  workflow_dispatch:

jobs:
  sync_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          repository: Yanyutin753/lobe-chat
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Sync upstream changes
        run: |
          # Fetch upstream changes
          git fetch --prune --unshallow upstream
          # Merge changes into the current branch
